FROM tensorflow/tensorflow:nightly

ENV APP_PATH="/app"
ENV JOB_NAME='keras_test_002'
ENV JOB_DIR='gs://co-oortiz-internal'
ENV GOOGLE_APPLICATION_CREDENTIALS="${APP_PATH}/service-key.json"

WORKDIR ${APP_PATH}

RUN pip install google-cloud-storage cloudml-hypertune pandas

COPY ./keras_training ${APP_PATH}
COPY ./keras_webapi/service-key.json ${APP_PATH}/

ENTRYPOINT python -m trainer.task  --job-name ${JOB_NAME} --train-files ${JOB_DIR}
#ENTRYPOINT ["python", "-m", "trainer.task",  "--job-name", "keras_test_002", "--train-files", "gs://co-oortiz-internal"]
